[programs.devnet]
pixsol = "11111111111111111111111111111111"  # Replace this with your deployed program ID after running `anchor deploy`

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["contracts/pixsol"]
